# Generated by Django 3.0.2 on 2020-05-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='thumbnial',
            new_name='thumbnail',
        ),
    ]
