# Generated by Django 3.0.2 on 2020-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200517_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-priority']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='position',
            new_name='priority',
        ),
    ]
